import type { AgentDef, VideoProject, KPIData } from '@/types'

// ── Final 14-Agent Workflow (in execution order) ──────────────────────────────
export const AGENT_DEFINITIONS: AgentDef[] = [
  // ── Row 1: Research & Intelligence ────────────────────────────────────────
  {
    id: 'agent-1',
    slug: 'trend-agent',
    name: 'Trend Scout',
    icon: '🔥',
    description: 'Autonomously monitors Reddit, HackerNews, Google News, YouTube, TikTok and Product Hunt to identify viral and high-potential topics before they peak.',
    input: 'Autonomous — no input required',
    output: 'Ranked trend list with opportunity scores, creator profiles, and predictions',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    lastRunMs: 3200,
    errorCount: 0,
    color: '#f59e0b',
    position: { x: 50, y: 80 },
  },
  {
    id: 'agent-2',
    slug: 'competitor-agent',
    name: 'Competitor Analyst',
    icon: '🕵️',
    description: 'Scrapes and analyzes top creators in a niche — hook patterns, video formats, hashtags, engagement metrics, and posting strategies.',
    input: 'Creator username or niche keyword',
    output: 'Competitor report: hooks, formats, hashtags, performance metrics',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    lastRunMs: 4100,
    errorCount: 0,
    color: '#8b5cf6',
    position: { x: 270, y: 80 },
  },
  {
    id: 'agent-3',
    slug: 'knowledge-agent',
    name: 'Knowledge Base',
    icon: '🧠',
    description: 'Internal memory of the entire system. Prevents duplicate topics, surfaces best-performing hooks and formats, and enriches new scripts with past learnings.',
    input: 'Topic + niche from Competitor Agent',
    output: 'Duplicate check, best hooks, successful formats, hashtag library',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    lastRunMs: 800,
    errorCount: 0,
    color: '#06b6d4',
    position: { x: 490, y: 80 },
  },
  // ── Row 2: Content Creation ────────────────────────────────────────────────
  {
    id: 'agent-4',
    slug: 'script-agent',
    name: 'Script Writer',
    icon: '✍️',
    description: 'Generates high-retention scripts enriched by competitor context and knowledge base insights. Niche-aware hooks, story arc, and CTA.',
    input: 'Topic, niche, competitor context, KB insights',
    output: 'Full script with hook, sections, CTA, hashtags, thumbnail idea',
    status: 'running',
    lastRun: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    lastRunMs: 4500,
    errorCount: 0,
    color: '#ec4899',
    position: { x: 50, y: 280 },
  },
  {
    id: 'agent-5',
    slug: 'seo-agent',
    name: 'SEO Optimizer',
    icon: '🔎',
    description: 'Maximizes discoverability on every platform. Generates YouTube titles, TikTok captions, Instagram descriptions, keywords, hashtags, hook variants, and alt titles.',
    input: 'Script output from Script Writer',
    output: 'Platform-specific SEO: titles, descriptions, tags, keywords, search terms',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    lastRunMs: 1200,
    errorCount: 0,
    color: '#10b981',
    position: { x: 270, y: 280 },
  },
  {
    id: 'agent-6',
    slug: 'brand-agent',
    name: 'Brand Consistency',
    icon: '🎨',
    description: 'Checks every video against the brand identity. Validates tone, hook strength, CTA quality, script length, and SEO alignment. Auto-fixes critical issues.',
    input: 'Script + SEO data',
    output: 'Brand score, check results, suggestions, auto-fixed CTA',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastRunMs: 600,
    errorCount: 0,
    color: '#f97316',
    position: { x: 490, y: 280 },
  },
  // ── Row 3: Production ──────────────────────────────────────────────────────
  {
    id: 'agent-7',
    slug: 'asset-manager-agent',
    name: 'Asset Manager',
    icon: '📦',
    description: 'Sources, licenses, and organizes stock footage, images, and audio. Verifies copyright status and creates a scene-by-scene asset manifest.',
    input: 'Brand-approved script, visual notes per section',
    output: 'Licensed asset manifest with download URLs and scene assignments',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    lastRunMs: 8900,
    errorCount: 2,
    lastError: 'Pexels API timeout on asset batch 3',
    color: '#a78bfa',
    position: { x: 50, y: 480 },
  },
  {
    id: 'agent-8',
    slug: 'video-agent',
    name: 'Video Composer',
    icon: '🎬',
    description: 'Assembles final video from assets, voiceover, subtitles and B-roll. Applies color grading and brand-consistent transitions. Renders 9:16 and 16:9.',
    input: 'Assets, voiceover, subtitles, brand guidelines',
    output: 'Rendered MP4 in 9:16 and 16:9 formats',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    lastRunMs: 45000,
    errorCount: 1,
    lastError: 'FFmpeg timeout on 4K render — fallback to 1080p',
    color: '#ef4444',
    position: { x: 270, y: 480 },
  },
  {
    id: 'agent-9',
    slug: 'qc-agent',
    name: 'QC Inspector',
    icon: '🔍',
    description: 'Automated quality control: audio sync, resolution, subtitle accuracy, hook timing, content policy, and brand guidelines compliance.',
    input: 'Rendered video, script, brand guidelines',
    output: 'QC report with pass/fail scores — blocks upload if critical issues found',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    lastRunMs: 6700,
    errorCount: 0,
    color: '#14b8a6',
    position: { x: 490, y: 480 },
  },
  // ── Row 4: Publishing ──────────────────────────────────────────────────────
  {
    id: 'agent-10',
    slug: 'calendar-agent',
    name: 'Content Calendar',
    icon: '📅',
    description: 'Decides when, where, and in what order content is published. Optimizes by platform peak times, timezone, audience, and past performance.',
    input: 'QC-approved video, niche, platforms',
    output: 'Publication schedule: platform, date/time, adaptations, estimated reach',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    lastRunMs: 900,
    errorCount: 0,
    color: '#84cc16',
    position: { x: 50, y: 680 },
  },
  {
    id: 'agent-11',
    slug: 'upload-agent',
    name: 'Upload Bot',
    icon: '🚀',
    description: 'Publishes videos exclusively according to the Content Calendar schedule — YouTube, Instagram Reels, and TikTok with platform-optimized metadata.',
    input: 'Calendar plan, video file, SEO metadata per platform',
    output: 'Upload confirmations with live platform URLs',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    lastRunMs: 18000,
    errorCount: 3,
    lastError: 'TikTok API rejected video: music copyright flag',
    color: '#3b82f6',
    position: { x: 270, y: 680 },
  },
  // ── Row 5: Learning Loop ───────────────────────────────────────────────────
  {
    id: 'agent-12',
    slug: 'analytics-agent',
    name: 'Analytics Brain',
    icon: '📊',
    description: 'Aggregates cross-platform performance metrics after upload. Identifies winning patterns, hooks, and posting times. Generates alerts.',
    input: 'Platform analytics APIs (YouTube, TikTok, Instagram)',
    output: 'Performance report, winning patterns, alerts, retention analysis',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastRunMs: 5200,
    errorCount: 0,
    color: '#22d3ee',
    position: { x: 490, y: 680 },
  },
  {
    id: 'agent-13',
    slug: 'engagement-agent',
    name: 'Engagement Analyzer',
    icon: '💬',
    description: 'Reads all community comments, extracts FAQs, content wishes, and trending requests. Generates new content ideas and reply suggestions.',
    input: 'Comments from all platforms, analytics report',
    output: 'Content ideas, FAQ list, community trends, reply suggestions, series opportunities',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    lastRunMs: 2100,
    errorCount: 0,
    color: '#f472b6',
    position: { x: 50, y: 880 },
  },
  {
    id: 'agent-14',
    slug: 'optimization-agent',
    name: 'Learning Agent',
    icon: '⚡',
    description: 'Synthesizes everything: analytics + engagement + KB. Updates hooks, posting rules, format weights, and agent parameters for continuous improvement.',
    input: 'Analytics report, engagement insights, knowledge base',
    output: 'Updated system rules, hook library improvements, parameter adjustments',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    lastRunMs: 2800,
    errorCount: 0,
    color: '#a3e635',
    position: { x: 270, y: 880 },
  },
]

export const DEMO_VIDEOS: VideoProject[] = [
  {
    id: 'vid-1',
    title: 'How AI Is Making Humans Obsolete (Faster Than You Think)',
    topic: 'AI replacing jobs',
    hook: 'In 90 days, 3 of your coworkers will be replaced by this...',
    script: 'HOOK: In 90 days, 3 of your coworkers will be replaced by this...\n\nSCENE 1: [Dramatic office B-roll] The stats are already terrifying. McKinsey says 375 million workers need to switch jobs by 2030.\n\nSCENE 2: [AI interface footage] But here\'s what no one\'s telling you — the jobs being automated first aren\'t what you expect.\n\nSCENE 3: [Data visualization] Accountants, paralegals, radiologists — white-collar jobs paying $80K+ are being hit hardest.\n\nCTA: Follow for daily AI updates that your company doesn\'t want you to see.',
    videoPrompt: 'Cinematic dark office environment, blue-purple color grade, fast cuts, corporate dystopia aesthetic',
    platforms: ['youtube', 'instagram', 'tiktok'],
    status: 'uploaded',
    qcScore: 94,
    qcPassed: true,
    uploadStatus: 'complete',
    youtubeUrl: 'https://youtube.com/shorts/demo1',
    instagramUrl: 'https://instagram.com/reels/demo1',
    tiktokUrl: 'https://tiktok.com/@demo/video/1',
    views: 284000,
    likes: 18200,
    comments: 3400,
    shares: 2100,
    watchtime: 42.3,
    retention: 67,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'vid-2',
    title: 'The $0 to $10K/Month Blueprint Nobody Shares',
    topic: 'Online income strategies',
    hook: 'I made $10,000 last month using only free tools. Here\'s exactly how.',
    script: 'HOOK: I made $10,000 last month using only free tools. Here\'s exactly how.\n\nSCENE 1: Show income screenshot. This is real. These are my actual numbers from last month.\n\nSCENE 2: Step 1 — Pick one platform. Don\'t spread yourself thin. YouTube Shorts or TikTok.\n\nSCENE 3: Step 2 — Use AI to 10x your output. I\'ll show you my exact workflow.\n\nCTA: Comment BLUEPRINT and I\'ll DM you the full system.',
    platforms: ['youtube', 'tiktok'],
    status: 'uploaded',
    qcScore: 88,
    qcPassed: true,
    uploadStatus: 'complete',
    youtubeUrl: 'https://youtube.com/shorts/demo2',
    tiktokUrl: 'https://tiktok.com/@demo/video/2',
    views: 156000,
    likes: 12400,
    comments: 8900,
    shares: 1800,
    watchtime: 38.1,
    retention: 71,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'vid-3',
    title: 'Why Your Brain Is Lying To You Every Morning',
    topic: 'Neuroscience / productivity',
    hook: 'Your morning routine is destroying your focus. A neuroscientist explains why.',
    platforms: ['youtube', 'instagram', 'tiktok'],
    status: 'rendering',
    qcScore: undefined,
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'vid-4',
    title: 'The Hidden Cost of Electric Vehicles in 2025',
    topic: 'EV reality check',
    hook: 'Before you buy an EV, watch this. The true cost will shock you.',
    platforms: ['youtube', 'tiktok'],
    status: 'scripting',
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
]

export const DEMO_KPI: KPIData = {
  videosToday: 3,
  successfulUploads: 2,
  failedUploads: 0,
  avgWatchtime: 40.2,
  bestPlatform: 'TikTok',
  activeAgents: 2,
  totalViews: 440000,
}

export const ALERTS = [
  { id: 1, level: 'warning', message: 'Asset Manager: Pexels API rate limit at 87% — consider switching to Pixabay fallback', time: '12m ago' },
  { id: 2, level: 'success', message: 'Video "AI Making Humans Obsolete" crossed 250K views on TikTok', time: '34m ago' },
  { id: 3, level: 'info', message: 'Optimizer updated hook formula — adding urgency trigger to pattern', time: '1h ago' },
  { id: 4, level: 'danger', message: 'Upload Bot: TikTok rejected video due to background music copyright — manual review needed', time: '3h ago' },
  { id: 5, level: 'success', message: 'Analytics Brain identified new viral pattern: "Before you X, watch this" hooks +34% retention', time: '4h ago' },
]
