import type { AgentDef, VideoProject, KPIData } from '@/types'

// ── Final 14-Agent Workflow (in execution order) ──────────────────────────────
export const AGENT_DEFINITIONS: AgentDef[] = [
  // ── Row 1: Research & Intelligence ────────────────────────────────────────
  {
    id: 'agent-1',
    slug: 'trend-agent',
    name: 'Trend Scout',
    icon: '🔥',
    description: 'Autonomously monitors Reddit, HackerNews, Google News, YouTube, TikTok and Product Hunt to identify viral and high-potential topics before they peak.',
    input: 'Autonomous — no input required',
    output: 'Ranked trend list with opportunity scores, creator profiles, and predictions',
    status: 'idle',
    errorCount: 0,
    color: '#f59e0b',
    position: { x: 50, y: 80 },
  },
  {
    id: 'agent-2',
    slug: 'competitor-agent',
    name: 'Competitor Analyst',
    icon: '🕵️',
    description: 'Analysiert Top-Creator in der Nische (Fashion, Lifestyle, Travel) — Hook-Muster, Video-Formate, Hashtags, Engagement-Metriken und Posting-Strategien.',
    input: 'Creator-Handle oder Nische (@69perception)',
    output: 'Competitor Report: Hooks, Formate, Hashtags, Performance-Metriken',
    status: 'idle',
    errorCount: 0,
    color: '#8b5cf6',
    position: { x: 270, y: 80 },
  },
  {
    id: 'agent-3',
    slug: 'knowledge-agent',
    name: 'Knowledge Base',
    icon: '🧠',
    description: 'Internes Gedächtnis des Systems. Verhindert doppelte Topics, liefert beste Hooks und Formate aus vergangenen Videos, angereichert mit Lerneffekten.',
    input: 'Topic + Nische vom Competitor Agent',
    output: 'Duplikat-Check, beste Hooks, erfolgreiche Formate, Hashtag-Bibliothek',
    status: 'idle',
    errorCount: 0,
    color: '#06b6d4',
    position: { x: 490, y: 80 },
  },
  // ── Row 2: Content Creation ────────────────────────────────────────────────
  {
    id: 'agent-4',
    slug: 'script-agent',
    name: 'Script Writer',
    icon: '✍️',
    description: 'Generiert High-Retention-Skripte im @69perception-Stil — cinematic, dunkel, motivational. Nischen-aware Hooks, Story-Arc und CTA für @killa_wp.',
    input: 'Topic, Nische, Competitor-Kontext, KB-Insights',
    output: 'Vollständiges Skript mit Hook, Abschnitten, CTA, Hashtags, Thumbnail-Idee',
    status: 'idle',
    errorCount: 0,
    color: '#ec4899',
    position: { x: 50, y: 280 },
  },
  {
    id: 'agent-5',
    slug: 'seo-agent',
    name: 'SEO Optimizer',
    icon: '🔎',
    description: 'Maximiert Auffindbarkeit auf allen Plattformen. Erstellt YouTube-Titel, TikTok-Captions, Instagram-Beschreibungen, Keywords, Hashtags und Hook-Varianten.',
    input: 'Script-Output vom Script Writer',
    output: 'Plattform-spezifisches SEO: Titel, Beschreibungen, Tags, Keywords, Suchbegriffe',
    status: 'idle',
    errorCount: 0,
    color: '#10b981',
    position: { x: 270, y: 280 },
  },
  {
    id: 'agent-6',
    slug: 'brand-agent',
    name: 'Brand Consistency',
    icon: '🎨',
    description: 'Prüft jedes Video gegen die Brand-Identität (@killa_wp). Validiert Ton, Hook-Stärke, CTA-Qualität, Skript-Länge und SEO-Alignment. Behebt kritische Issues.',
    input: 'Skript + SEO-Daten',
    output: 'Brand-Score, Check-Ergebnisse, Vorschläge, Auto-Fix CTA',
    status: 'idle',
    errorCount: 0,
    color: '#f97316',
    position: { x: 490, y: 280 },
  },
  // ── Row 3: Production ──────────────────────────────────────────────────────
  {
    id: 'agent-7',
    slug: 'asset-manager-agent',
    name: 'Asset Manager',
    icon: '📦',
    description: 'Sucht und lizenziert Stock-Videos und Fotos via Pexels API. Keywords werden aus der Nische abgeleitet (Luxury Lifestyle, Urban Cinematic, Fashion Editorial).',
    input: 'Brand-geprüftes Skript, visuelle Notizen pro Abschnitt',
    output: 'Lizenziertes Asset-Manifest mit Download-URLs und Szenen-Zuweisungen',
    status: 'idle',
    errorCount: 0,
    color: '#a78bfa',
    position: { x: 50, y: 480 },
  },
  {
    id: 'agent-8',
    slug: 'video-agent',
    name: 'InVideo AI Agent',
    icon: '🎬',
    description: 'Steuert InVideo AI via Browser-Automatisierung (Puppeteer). Gibt Script-Prompt ein, wartet auf KI-Video-Generierung (Veo 3.1 / Kling 3.0), lädt fertiges MP4 herunter.',
    input: 'Skript, Topic, Hook vom Script Writer',
    output: 'Heruntergeladenes MP4 (9:16 vertikal) bereit für QC',
    status: 'idle',
    errorCount: 0,
    color: '#ef4444',
    position: { x: 270, y: 480 },
  },
  {
    id: 'agent-9',
    slug: 'qc-agent',
    name: 'QC Inspector',
    icon: '🔍',
    description: 'Automatisierte Qualitätskontrolle: Hook-Stärke, Script-Qualität, Brand-Konsistenz, Content-Policy und Platform-Optimierung. Blockiert Upload bei kritischen Issues.',
    input: 'Gerendertes Video, Skript, Brand Guidelines',
    output: 'QC-Report mit Pass/Fail-Scores — blockiert Upload bei kritischen Issues',
    status: 'idle',
    errorCount: 0,
    color: '#14b8a6',
    position: { x: 490, y: 480 },
  },
  // ── Row 4: Publishing ──────────────────────────────────────────────────────
  {
    id: 'agent-10',
    slug: 'calendar-agent',
    name: 'Content Calendar',
    icon: '📅',
    description: 'Entscheidet wann, wo und in welcher Reihenfolge Content published wird. Optimiert nach Platform-Peak-Times (18–20 Uhr), Zeitzone und bisheriger Performance.',
    input: 'QC-geprüftes Video, Nische, Plattformen',
    output: 'Veröffentlichungsplan: Plattform, Datum/Uhrzeit, Anpassungen, geschätzte Reichweite',
    status: 'idle',
    errorCount: 0,
    color: '#84cc16',
    position: { x: 50, y: 680 },
  },
  {
    id: 'agent-11',
    slug: 'upload-agent',
    name: 'Upload Bot',
    icon: '🚀',
    description: 'Publiziert Videos gemäß Content Calendar — YouTube (API), Instagram Reels und TikTok mit plattform-optimierten Metadaten. YouTube API bereits konfiguriert.',
    input: 'Kalenderplan, Video-Datei, SEO-Metadaten pro Plattform',
    output: 'Upload-Bestätigungen mit Live-Platform-URLs',
    status: 'idle',
    errorCount: 0,
    color: '#3b82f6',
    position: { x: 270, y: 680 },
  },
  // ── Row 5: Learning Loop ───────────────────────────────────────────────────
  {
    id: 'agent-12',
    slug: 'analytics-agent',
    name: 'Analytics Brain',
    icon: '📊',
    description: 'Aggregiert plattformübergreifende Performance-Metriken nach dem Upload. Identifiziert Winning-Patterns, beste Hooks und Posting-Zeiten. Generiert Alerts.',
    input: 'Plattform-Analytics-APIs (YouTube, TikTok, Instagram)',
    output: 'Performance-Report, Winning-Patterns, Alerts, Retention-Analyse',
    status: 'idle',
    errorCount: 0,
    color: '#22d3ee',
    position: { x: 490, y: 680 },
  },
  {
    id: 'agent-13',
    slug: 'engagement-agent',
    name: 'Engagement Analyzer',
    icon: '💬',
    description: 'Liest Community-Kommentare, extrahiert FAQs, Content-Wünsche und Trending-Anfragen. Generiert neue Content-Ideen und Antwort-Vorschläge.',
    input: 'Kommentare aller Plattformen, Analytics-Report',
    output: 'Content-Ideen, FAQ-Liste, Community-Trends, Antwort-Vorschläge, Serien-Chancen',
    status: 'idle',
    errorCount: 0,
    color: '#f472b6',
    position: { x: 50, y: 880 },
  },
  {
    id: 'agent-14',
    slug: 'optimization-agent',
    name: 'Learning Agent',
    icon: '⚡',
    description: 'Synthetisiert alles: Analytics + Engagement + KB. Aktualisiert Hooks, Posting-Regeln, Format-Gewichtungen und Agent-Parameter für kontinuierliche Verbesserung.',
    input: 'Analytics-Report, Engagement-Insights, Knowledge Base',
    output: 'Aktualisierte System-Regeln, Hook-Bibliothek-Verbesserungen, Parameter-Anpassungen',
    status: 'idle',
    errorCount: 0,
    color: '#a3e635',
    position: { x: 270, y: 880 },
  },
]

export const DEMO_VIDEOS: VideoProject[] = [
  {
    id: 'vid-1',
    title: 'Die Leute die am wenigsten reden bauen am meisten auf',
    topic: 'Lifestyle / Personal Brand',
    hook: 'Die Leute die am wenigsten reden — bauen am meisten auf.',
    script: 'HOOK: Die Leute die am wenigsten reden — bauen am meisten auf.\n\nMONTAGE: Kein Drama. Keine Ausreden. Nur Fokus. Nur Bewegung. Jeden Tag. Ohne Publikum.\n\nCTA: Build different. @killa_wp',
    videoPrompt: 'Cinematic dark moody montage. Urban environments, luxury lifestyle, fashion details. Fast cuts synced to beat. Warm color grading.',
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'uploaded',
    qcScore: 94,
    qcPassed: true,
    uploadStatus: 'complete',
    instagramUrl: 'https://instagram.com/reels/demo1',
    tiktokUrl: 'https://tiktok.com/@killa_wp/video/1',
    youtubeUrl: 'https://youtube.com/shorts/demo1',
    views: 284000,
    likes: 18200,
    comments: 3400,
    shares: 2100,
    watchtime: 24.3,
    retention: 71,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'vid-2',
    title: 'Dein Lifestyle ist deine stärkste Message',
    topic: 'Personal Brand / Aesthetic',
    hook: 'Dein Lifestyle erzählt mehr über dich als jedes Wort das du je sagst.',
    script: 'HOOK: Dein Lifestyle erzählt mehr über dich als jedes Wort das du je sagst.\n\nMONTAGE: Golden hour. Cinematic shots. Mode. Reisen. Fokus. Das ist deine Marke.\n\nCTA: Follow für mehr.',
    videoPrompt: 'Fashion details close-up, travel shots, city skyline. @69perception aesthetic. Dark warm tones.',
    platforms: ['instagram', 'tiktok'],
    status: 'uploaded',
    qcScore: 91,
    qcPassed: true,
    uploadStatus: 'complete',
    instagramUrl: 'https://instagram.com/reels/demo2',
    tiktokUrl: 'https://tiktok.com/@killa_wp/video/2',
    views: 156000,
    likes: 12400,
    comments: 2100,
    shares: 1800,
    watchtime: 22.1,
    retention: 68,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'vid-3',
    title: 'Niemand erinnert sich an den Durchschnitt',
    topic: 'Motivation / Lifestyle',
    hook: 'Niemand erinnert sich an den Durchschnitt. Sei außergewöhnlich.',
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'rendering',
    qcScore: undefined,
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'vid-4',
    title: 'Stille ist die lauteste Form von Selbstbewusstsein',
    topic: 'Mindset / Personal Brand',
    hook: 'Stille ist die lauteste Form von Selbstbewusstsein.',
    platforms: ['instagram', 'tiktok'],
    status: 'scripting',
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
]

export const DEMO_KPI: KPIData = {
  videosToday: 3,
  successfulUploads: 2,
  failedUploads: 0,
  avgWatchtime: 23.2,
  bestPlatform: 'Instagram',
  activeAgents: 4,
  totalViews: 440000,
}

export const ALERTS = [
  { id: 1, level: 'success', message: 'Video "Die Leute die am wenigsten reden" — 284K Views auf Instagram Reels', time: '12m ago' },
  { id: 2, level: 'info', message: 'Trend Scout: "Stille als Stärke" Trend steigt — Hook-Variante bereit', time: '34m ago' },
  { id: 3, level: 'warning', message: 'Asset Manager: Pexels Limit bei 82% — Pixabay Fallback aktiv', time: '1h ago' },
  { id: 4, level: 'success', message: 'InVideo AI: Video "Dein Lifestyle" erfolgreich generiert (28 Sek.)', time: '2h ago' },
  { id: 5, level: 'info', message: 'Script Agent: Neues Hook-Muster erkannt — "Niemand erinnert sich an..." +41% Retention', time: '3h ago' },
]
