import type { AgentDef, VideoProject, KPIData } from '@/types'

// ── Final 14-Agent Workflow (in execution order) ──────────────────────────────
export const AGENT_DEFINITIONS: AgentDef[] = [
  // ── Row 1: Research & Intelligence ────────────────────────────────────────
  {
    id: 'agent-1',
    slug: 'trend-agent',
    name: 'Trend Scout',
    icon: '🔥',
    description: 'Autonomously monitors Reddit, HackerNews, Google News, YouTube, TikTok and Product Hunt to identify viral and high-potential topics before they peak.',
    input: 'Autonomous — no input required',
    output: 'Ranked trend list with opportunity scores, creator profiles, and predictions',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    lastRunMs: 3200,
    errorCount: 0,
    color: '#f59e0b',
    position: { x: 50, y: 80 },
  },
  {
    id: 'agent-2',
    slug: 'competitor-agent',
    name: 'Competitor Analyst',
    icon: '🕵️',
    description: 'Scrapes and analyzes top creators in a niche — hook patterns, video formats, hashtags, engagement metrics, and posting strategies.',
    input: 'Creator username or niche keyword',
    output: 'Competitor report: hooks, formats, hashtags, performance metrics',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    lastRunMs: 4100,
    errorCount: 0,
    color: '#8b5cf6',
    position: { x: 270, y: 80 },
  },
  {
    id: 'agent-3',
    slug: 'knowledge-agent',
    name: 'Knowledge Base',
    icon: '🧠',
    description: 'Internal memory of the entire system. Prevents duplicate topics, surfaces best-performing hooks and formats, and enriches new scripts with past learnings.',
    input: 'Topic + niche from Competitor Agent',
    output: 'Duplicate check, best hooks, successful formats, hashtag library',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    lastRunMs: 800,
    errorCount: 0,
    color: '#06b6d4',
    position: { x: 490, y: 80 },
  },
  // ── Row 2: Content Creation ────────────────────────────────────────────────
  {
    id: 'agent-4',
    slug: 'script-agent',
    name: 'Script Writer',
    icon: '✍️',
    description: 'Generates high-retention scripts enriched by competitor context and knowledge base insights. Niche-aware hooks, story arc, and CTA.',
    input: 'Topic, niche, competitor context, KB insights',
    output: 'Full script with hook, sections, CTA, hashtags, thumbnail idea',
    status: 'running',
    lastRun: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    lastRunMs: 4500,
    errorCount: 0,
    color: '#ec4899',
    position: { x: 50, y: 280 },
  },
  {
    id: 'agent-5',
    slug: 'seo-agent',
    name: 'SEO Optimizer',
    icon: '🔎',
    description: 'Maximizes discoverability on every platform. Generates YouTube titles, TikTok captions, Instagram descriptions, keywords, hashtags, hook variants, and alt titles.',
    input: 'Script output from Script Writer',
    output: 'Platform-specific SEO: titles, descriptions, tags, keywords, search terms',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    lastRunMs: 1200,
    errorCount: 0,
    color: '#10b981',
    position: { x: 270, y: 280 },
  },
  {
    id: 'agent-6',
    slug: 'brand-agent',
    name: 'Brand Consistency',
    icon: '🎨',
    description: 'Checks every video against the brand identity. Validates tone, hook strength, CTA quality, script length, and SEO alignment. Auto-fixes critical issues.',
    input: 'Script + SEO data',
    output: 'Brand score, check results, suggestions, auto-fixed CTA',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastRunMs: 600,
    errorCount: 0,
    color: '#f97316',
    position: { x: 490, y: 280 },
  },
  // ── Row 3: Production ──────────────────────────────────────────────────────
  {
    id: 'agent-7',
    slug: 'asset-manager-agent',
    name: 'Asset Manager',
    icon: '📦',
    description: 'Sources, licenses, and organizes stock footage, images, and audio. Verifies copyright status and creates a scene-by-scene asset manifest.',
    input: 'Brand-approved script, visual notes per section',
    output: 'Licensed asset manifest with download URLs and scene assignments',
    status: 'waiting',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    lastRunMs: 8900,
    errorCount: 2,
    lastError: 'Pexels API timeout on asset batch 3',
    color: '#a78bfa',
    position: { x: 50, y: 480 },
  },
  {
    id: 'agent-8',
    slug: 'video-agent',
    name: 'InVideo AI Agent',
    icon: '🎬',
    description: 'Controls InVideo AI via browser automation. Enters the script prompt, waits for AI video generation (Veo 3.1 / Kling 3.0 / Seedance 2.0), downloads finished MP4. Cinematic dark montage style à la @69perception.',
    input: 'Script, topic, hook from Script Writer',
    output: 'Downloaded MP4 (9:16 vertical) ready for QC',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    lastRunMs: 45000,
    errorCount: 1,
    lastError: 'FFmpeg timeout on 4K render — fallback to 1080p',
    color: '#ef4444',
    position: { x: 270, y: 480 },
  },
  {
    id: 'agent-9',
    slug: 'qc-agent',
    name: 'QC Inspector',
    icon: '🔍',
    description: 'Automated quality control: audio sync, resolution, subtitle accuracy, hook timing, content policy, and brand guidelines compliance.',
    input: 'Rendered video, script, brand guidelines',
    output: 'QC report with pass/fail scores — blocks upload if critical issues found',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    lastRunMs: 6700,
    errorCount: 0,
    color: '#14b8a6',
    position: { x: 490, y: 480 },
  },
  // ── Row 4: Publishing ──────────────────────────────────────────────────────
  {
    id: 'agent-10',
    slug: 'calendar-agent',
    name: 'Content Calendar',
    icon: '📅',
    description: 'Decides when, where, and in what order content is published. Optimizes by platform peak times, timezone, audience, and past performance.',
    input: 'QC-approved video, niche, platforms',
    output: 'Publication schedule: platform, date/time, adaptations, estimated reach',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    lastRunMs: 900,
    errorCount: 0,
    color: '#84cc16',
    position: { x: 50, y: 680 },
  },
  {
    id: 'agent-11',
    slug: 'upload-agent',
    name: 'Upload Bot',
    icon: '🚀',
    description: 'Publishes videos exclusively according to the Content Calendar schedule — YouTube, Instagram Reels, and TikTok with platform-optimized metadata.',
    input: 'Calendar plan, video file, SEO metadata per platform',
    output: 'Upload confirmations with live platform URLs',
    status: 'idle',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    lastRunMs: 18000,
    errorCount: 3,
    lastError: 'TikTok API rejected video: music copyright flag',
    color: '#3b82f6',
    position: { x: 270, y: 680 },
  },
  // ── Row 5: Learning Loop ───────────────────────────────────────────────────
  {
    id: 'agent-12',
    slug: 'analytics-agent',
    name: 'Analytics Brain',
    icon: '📊',
    description: 'Aggregates cross-platform performance metrics after upload. Identifies winning patterns, hooks, and posting times. Generates alerts.',
    input: 'Platform analytics APIs (YouTube, TikTok, Instagram)',
    output: 'Performance report, winning patterns, alerts, retention analysis',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastRunMs: 5200,
    errorCount: 0,
    color: '#22d3ee',
    position: { x: 490, y: 680 },
  },
  {
    id: 'agent-13',
    slug: 'engagement-agent',
    name: 'Engagement Analyzer',
    icon: '💬',
    description: 'Reads all community comments, extracts FAQs, content wishes, and trending requests. Generates new content ideas and reply suggestions.',
    input: 'Comments from all platforms, analytics report',
    output: 'Content ideas, FAQ list, community trends, reply suggestions, series opportunities',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    lastRunMs: 2100,
    errorCount: 0,
    color: '#f472b6',
    position: { x: 50, y: 880 },
  },
  {
    id: 'agent-14',
    slug: 'optimization-agent',
    name: 'Learning Agent',
    icon: '⚡',
    description: 'Synthesizes everything: analytics + engagement + KB. Updates hooks, posting rules, format weights, and agent parameters for continuous improvement.',
    input: 'Analytics report, engagement insights, knowledge base',
    output: 'Updated system rules, hook library improvements, parameter adjustments',
    status: 'success',
    lastRun: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    lastRunMs: 2800,
    errorCount: 0,
    color: '#a3e635',
    position: { x: 270, y: 880 },
  },
]

export const DEMO_VIDEOS: VideoProject[] = [
  {
    id: 'vid-1',
    title: 'Die Leute die am wenigsten reden bauen am meisten auf',
    topic: 'Lifestyle / Personal Brand',
    hook: 'Die Leute die am wenigsten reden — bauen am meisten auf.',
    script: 'HOOK: Die Leute die am wenigsten reden — bauen am meisten auf.\n\nMONTAGE: Kein Drama. Keine Ausreden. Nur Fokus. Nur Bewegung. Jeden Tag. Ohne Publikum.\n\nCTA: Build different. @killa_wp',
    videoPrompt: 'Cinematic dark moody montage. Urban environments, luxury lifestyle, fashion details. Fast cuts synced to beat. Warm color grading.',
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'uploaded',
    qcScore: 94,
    qcPassed: true,
    uploadStatus: 'complete',
    instagramUrl: 'https://instagram.com/reels/demo1',
    tiktokUrl: 'https://tiktok.com/@killa_wp/video/1',
    youtubeUrl: 'https://youtube.com/shorts/demo1',
    views: 284000,
    likes: 18200,
    comments: 3400,
    shares: 2100,
    watchtime: 24.3,
    retention: 71,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'vid-2',
    title: 'Dein Lifestyle ist deine stärkste Message',
    topic: 'Personal Brand / Aesthetic',
    hook: 'Dein Lifestyle erzählt mehr über dich als jedes Wort das du je sagst.',
    script: 'HOOK: Dein Lifestyle erzählt mehr über dich als jedes Wort das du je sagst.\n\nMONTAGE: Golden hour. Cinematic shots. Mode. Reisen. Fokus. Das ist deine Marke.\n\nCTA: Follow für mehr.',
    videoPrompt: 'Fashion details close-up, travel shots, city skyline. @69perception aesthetic. Dark warm tones.',
    platforms: ['instagram', 'tiktok'],
    status: 'uploaded',
    qcScore: 91,
    qcPassed: true,
    uploadStatus: 'complete',
    instagramUrl: 'https://instagram.com/reels/demo2',
    tiktokUrl: 'https://tiktok.com/@killa_wp/video/2',
    views: 156000,
    likes: 12400,
    comments: 2100,
    shares: 1800,
    watchtime: 22.1,
    retention: 68,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'vid-3',
    title: 'Niemand erinnert sich an den Durchschnitt',
    topic: 'Motivation / Lifestyle',
    hook: 'Niemand erinnert sich an den Durchschnitt. Sei außergewöhnlich.',
    platforms: ['instagram', 'tiktok', 'youtube'],
    status: 'rendering',
    qcScore: undefined,
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'vid-4',
    title: 'Stille ist die lauteste Form von Selbstbewusstsein',
    topic: 'Mindset / Personal Brand',
    hook: 'Stille ist die lauteste Form von Selbstbewusstsein.',
    platforms: ['instagram', 'tiktok'],
    status: 'scripting',
    qcPassed: false,
    uploadStatus: 'pending',
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    watchtime: 0,
    retention: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
]

export const DEMO_KPI: KPIData = {
  videosToday: 3,
  successfulUploads: 2,
  failedUploads: 0,
  avgWatchtime: 23.2,
  bestPlatform: 'Instagram',
  activeAgents: 4,
  totalViews: 440000,
}

export const ALERTS = [
  { id: 1, level: 'success', message: 'Video "Die Leute die am wenigsten reden" — 284K Views auf Instagram Reels', time: '12m ago' },
  { id: 2, level: 'info', message: 'Trend Scout: "Stille als Stärke" Trend steigt — Hook-Variante bereit', time: '34m ago' },
  { id: 3, level: 'warning', message: 'Asset Manager: Pexels Limit bei 82% — Pixabay Fallback aktiv', time: '1h ago' },
  { id: 4, level: 'success', message: 'InVideo AI: Video "Dein Lifestyle" erfolgreich generiert (28 Sek.)', time: '2h ago' },
  { id: 5, level: 'info', message: 'Script Agent: Neues Hook-Muster erkannt — "Niemand erinnert sich an..." +41% Retention', time: '3h ago' },
]
